meta_product_name: "ABY See"
meta_title: "ABY See - Creativity Flows"
meta_description: "Interactive Moodboards"
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
